/*
 * This source file was generated by the Gradle 'init' task
 */
package enumutil;

import enumutil.types.EnumUtil;
import enumutil.types.impl.CarType;

public class App {
    public String getGreeting() {
        return "Generic Enum Utility Example";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    
        System.out.println(
            "HashCode of SUV: " +
            EnumUtil.getHashCodeByCode(CarType.class, "SUV_1") + "\n" +
            "IDE is Visual Studio Code with Gradle Support extension.\n" + 
            "Build tool is Gradle 8.5\n" +
            "Java version is OpenJDK 21\n" +
            "EnumUtil project version is 0.0.1\n"
        );
        

        switch (EnumUtil.getConstantByCode(CarType.class, "SUV_1")) {
            case SEDAN:
                System.out.println("This is a sedan.");
                break;
            case SUV:
                System.out.println("This is an SUV.");
                break;
            case TRUCK:
                System.out.println("This is a truck.");
                break;
            case COUPE:
                System.out.println("This is a coupe.");
                break;
            case CONVERTIBLE:
                System.out.println("This is a convertible.");
                break;
            default:
                break;
        }
    }
}
